
import { Currency } from "../types/expenses";

export const currencyList: Currency[] = [
  { code: "AFN", symbol: "؋", name: "Afghan Afghani" },
  { code: "ALL", symbol: "L", name: "Albanian Lek" },
  { code: "DZD", symbol: "د.ج", name: "Algerian Dinar" },
  { code: "AOA", symbol: "Kz", name: "Angolan Kwanza" },
  { code: "ARS", symbol: "$", name: "Argentine Peso" },
  { code: "AMD", symbol: "֏", name: "Armenian Dram" },
  { code: "AUD", symbol: "$", name: "Australian Dollar" },
  { code: "EUR", symbol: "€", name: "Euro" },
  { code: "AZN", symbol: "₼", name: "Azerbaijani Manat" },
  { code: "BSD", symbol: "$", name: "Bahamian Dollar" },
  { code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka" },
  { code: "BBD", symbol: "$", name: "Barbadian Dollar" },
  { code: "BYN", symbol: "Br", name: "Belarusian Ruble" },
  { code: "BZD", symbol: "BZ$", name: "Belize Dollar" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc" },
  { code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum" },
  { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano" },
  { code: "BAM", symbol: "KM", name: "Convertible Mark" },
  { code: "BWP", symbol: "P", name: "Botswana Pula" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real" },
  { code: "BND", symbol: "$", name: "Brunei Dollar" },
  { code: "BGN", symbol: "лв", name: "Bulgarian Lev" },
  { code: "BIF", symbol: "FBu", name: "Burundian Franc" },
  { code: "KHR", symbol: "៛", name: "Cambodian Riel" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc" },
  { code: "CAD", symbol: "$", name: "Canadian Dollar" },
  { code: "CVE", symbol: "$", name: "Cape Verdean Escudo" },
  { code: "CLP", symbol: "$", name: "Chilean Peso" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan" },
  { code: "COP", symbol: "$", name: "Colombian Peso" },
  { code: "KMF", symbol: "CF", name: "Comorian Franc" },
  { code: "CDF", symbol: "FC", name: "Congolese Franc" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón" },
  { code: "CUP", symbol: "₱", name: "Cuban Peso" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna" },
  { code: "DKK", symbol: "kr", name: "Danish Krone" },
  { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar" },
  { code: "DOP", symbol: "RD$", name: "Dominican Peso" },
  { code: "USD", symbol: "$", name: "United States Dollar" },
  { code: "EGP", symbol: "£", name: "Egyptian Pound" },
  { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa" },
  { code: "SZL", symbol: "E", name: "Swazi Lilangeni" },
  { code: "ETB", symbol: "Br", name: "Ethiopian Birr" },
  { code: "FJD", symbol: "$", name: "Fijian Dollar" },
  { code: "GMD", symbol: "D", name: "Gambian Dalasi" },
  { code: "GEL", symbol: "₾", name: "Georgian Lari" },
  { code: "GHS", symbol: "₵", name: "Ghanaian Cedi" },
  { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal" },
  { code: "GNF", symbol: "FG", name: "Guinean Franc" },
  { code: "GYD", symbol: "$", name: "Guyanese Dollar" },
  { code: "HTG", symbol: "G", name: "Haitian Gourde" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint" },
  { code: "ISK", symbol: "kr", name: "Icelandic Króna" },
  { code: "INR", symbol: "₹", name: "Indian Rupee" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah" },
  { code: "IRR", symbol: "﷼", name: "Iranian Rial" },
  { code: "IQD", symbol: "ع.د", name: "Iraqi Dinar" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel" },
  { code: "JMD", symbol: "J$", name: "Jamaican Dollar" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen" },
  { code: "JOD", symbol: "JD", name: "Jordanian Dinar" },
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge" },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling" },
  { code: "KPW", symbol: "₩", name: "North Korean Won" },
  { code: "KRW", symbol: "₩", name: "South Korean Won" },
  { code: "KWD", symbol: "KD", name: "Kuwaiti Dinar" },
  { code: "KGS", symbol: "с", name: "Kyrgyzstani Som" },
  { code: "LAK", symbol: "₭", name: "Lao Kip" },
  { code: "LBP", symbol: "ل.ل", name: "Lebanese Pound" },
  { code: "LSL", symbol: "M", name: "Lesotho Loti" },
  { code: "LRD", symbol: "$", name: "Liberian Dollar" },
  { code: "LYD", symbol: "ل.د", name: "Libyan Dinar" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary" },
  { code: "MWK", symbol: "MK", name: "Malawian Kwacha" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit" },
  { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa" },
  { code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya" },
  { code: "MUR", symbol: "₨", name: "Mauritian Rupee" },
  { code: "MXN", symbol: "$", name: "Mexican Peso" },
  { code: "MDL", symbol: "L", name: "Moldovan Leu" },
  { code: "MNT", symbol: "₮", name: "Mongolian Tögrög" },
  { code: "MAD", symbol: "DH", name: "Moroccan Dirham" },
  { code: "MZN", symbol: "MT", name: "Mozambican Metical" },
  { code: "MMK", symbol: "K", name: "Burmese Kyat" },
  { code: "NAD", symbol: "$", name: "Namibian Dollar" },
  { code: "NPR", symbol: "₨", name: "Nepalese Rupee" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar" },
  { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { code: "MKD", symbol: "ден", name: "Macedonian Denar" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone" },
  { code: "OMR", symbol: "ر.ع.", name: "Omani Rial" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee" },
  { code: "PAB", symbol: "B/.", name: "Panamanian Balboa" },
  { code: "PGK", symbol: "K", name: "Papua New Guinean Kina" },
  { code: "PYG", symbol: "₲", name: "Paraguayan Guaraní" },
  { code: "PEN", symbol: "S/", name: "Peruvian Sol" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso" },
  { code: "PLN", symbol: "zł", name: "Polish Złoty" },
  { code: "QAR", symbol: "ر.ق", name: "Qatari Riyal" },
  { code: "RON", symbol: "lei", name: "Romanian Leu" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble" },
  { code: "RWF", symbol: "FRw", name: "Rwandan Franc" },
  { code: "WST", symbol: "WS$", name: "Samoan Tala" },
  { code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra" },
  { code: "SAR", symbol: "ر.س", name: "Saudi Riyal" },
  { code: "RSD", symbol: "дин.", name: "Serbian Dinar" },
  { code: "SCR", symbol: "₨", name: "Seychellois Rupee" },
  { code: "SLL", symbol: "Le", name: "Sierra Leonean Leone" },
  { code: "SGD", symbol: "$", name: "Singapore Dollar" },
  { code: "SBD", symbol: "$", name: "Solomon Islands Dollar" },
  { code: "SOS", symbol: "Sh", name: "Somali Shilling" },
  { code: "ZAR", symbol: "R", name: "South African Rand" },
  { code: "SSP", symbol: "£", name: "South Sudanese Pound" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee" },
  { code: "SDG", symbol: "ج.س.", name: "Sudanese Pound" },
  { code: "SRD", symbol: "$", name: "Surinamese Dollar" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona" },
  { code: "SYP", symbol: "£", name: "Syrian Pound" },
  { code: "TWD", symbol: "NT$", name: "New Taiwan Dollar" },
  { code: "TJS", symbol: "ЅМ", name: "Tajikistani Somoni" },
  { code: "TZS", symbol: "TSh", name: "Tanzanian Shilling" },
  { code: "THB", symbol: "฿", name: "Thai Baht" },
  { code: "TOP", symbol: "T$", name: "Tongan Paʻanga" },
  { code: "TTD", symbol: "TT$", name: "Trinidad and Tobago Dollar" },
  { code: "TND", symbol: "د.ت", name: "Tunisian Dinar" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira" },
  { code: "TMT", symbol: "m", name: "Turkmenistan Manat" },
  { code: "UGX", symbol: "USh", name: "Ugandan Shilling" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia" },
  { code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham" },
  { code: "UYU", symbol: "$U", name: "Uruguayan Peso" },
  { code: "UZS", symbol: "лв", name: "Uzbekistani Som" },
  { code: "VUV", symbol: "VT", name: "Vanuatu Vatu" },
  { code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar Soberano" },
  { code: "VND", symbol: "₫", name: "Vietnamese Đồng" },
  { code: "YER", symbol: "﷼", name: "Yemeni Rial" },
  { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha" },
  { code: "ZWL", symbol: "$", name: "Zimbabwean Dollar" }
];

export const getCurrencySymbol = (code: string): string => {
  const currency = currencyList.find(c => c.code === code);
  return currency ? currency.symbol : "$";
};

export const groupCurrenciesByRegion = () => {
  const regions = {
    americas: ["USD", "CAD", "MXN", "BRL", "ARS", "CLP", "PEN", "COP", "VES", "BOB", "UYU", "PYG", "GTQ", "HNL", "NIO", "CRC", "PAB", "DOP", "JMD", "TTD", "BSD", "BBD", "BZD", "GYD", "SRD"],
    europe: ["EUR", "GBP", "CHF", "SEK", "NOK", "DKK", "PLN", "CZK", "HUF", "RON", "BGN", "HRK", "RSD", "ALL", "MKD", "ISK"],
    asia: ["JPY", "CNY", "INR", "KRW", "IDR", "SGD", "THB", "MYR", "PHP", "VND", "PKR", "BDT", "LKR", "NPR", "MMK", "KHR", "LAK", "BND", "MNT", "KZT", "UZS", "TJS", "KGS", "TMT", "ILS", "JOD", "LBP", "SYP", "IRR", "IQD", "QAR", "BHD", "KWD", "OMR", "YER", "AED", "SAR"],
    africa: ["ZAR", "EGP", "NGN", "GHS", "KES", "TZS", "UGX", "RWF", "ETB", "MAD", "TND", "DZD", "LYD", "SDG", "XOF", "XAF", "SLL", "GMD", "MGA", "MWK", "ZMW", "BWP", "NAD", "MZN", "AOA", "CVE"],
    oceania: ["AUD", "NZD", "FJD", "PGK", "SBD", "VUV", "TOP", "WST"]
  };

  return regions;
};

export const getCurrenciesByRegion = (region: string): Currency[] => {
  const regions = groupCurrenciesByRegion();
  const regionCodes = regions[region as keyof typeof regions] || [];
  
  return currencyList.filter(currency => regionCodes.includes(currency.code));
};

export const getPopularCurrencies = (): Currency[] => {
  const popularCodes = ["USD", "EUR", "GBP", "JPY", "CNY", "INR", "CAD", "AUD", "CHF", "HKD", "SGD", "AED"];
  return currencyList.filter(currency => popularCodes.includes(currency.code));
};
